test to see that backend tests runs even if frontend fails

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,10 +26,20 @@ jobs:
 
     - name: Check frontend TypeScript build
       run: docker exec --workdir /var/www/html frontend npm run build
+      continue-on-error: true # Allow failure for frontend build, so backend can still run
 
     - name: Run backend ESLint (ESLint 9 flat config)
       run: docker exec --workdir /backend backend npx eslint ./srcs
+      continue-on-error: true # Allow failure for ESLint, so we can still run tests
 
+    # - name: Run backend tests
+    #   run: docker exec --workdir /backend backend npm run test
+    #   continue-on-error: true # Allow failure for tests, so we can still check lint
+
+    - name: Fail if previous steps had errors
+      run: exit 1
+      if: ${{ failure() }}
+      
     - name: Shutdown containers
       if: always()
       run: make down
